/// Retained non-optional base surface. Historical catalog snapshots may record
/// this set, but they are archive artifacts rather than alternate active runtime
/// versions. `runtime_tool_catalog` is the single client-visible composition path.
/// Local Git orchestration and LSP/code-intelligence calls remain implemented for
/// internal validation/bridge code, while ordinary agents use the terminal for
/// those workflows. Remote Git delivery stays on the credential-isolated tools.
pub const RETAINED_TOOL_NAMES: &[&str] = &[
    "terminal_exec",
    "ssh_readonly_exec",
    "http_fetch",
    "web_search",
    "directory_list",
    "file_search",
    "file_write",
    "file_edit",
    "file_read",
    "file_read_multiple",
    "text_search",
    "apply_patch",
    "git_remote_list",
    "git_remote_branch_get",
    "git_fetch",
    "git_push",
    "workspace_bootstrap",
    "workspace_add",
    "workspace_list",
    "workspace_get",
    "workspace_remove",
    "change_request_list",
    "change_request_get",
    "change_request_create",
    "change_request_update",
    "change_request_checks",
    "change_request_merge",
    "telegram_send_message",
    "issue_list",
    "issue_get",
    "issue_create",
    "issue_update",
    "issue_comment",
    "issue_close",
    "issue_reopen",
    "workflow_list",
    "workflow_get",
    "workflow_run_list",
    "workflow_run_get",
    "workflow_run_jobs",
    "workflow_job_log_preview",
    "dependabot_alert_list",
    "dependabot_alert_get",
    "code_scanning_alert_list",
    "code_scanning_alert_get",
    "secret_scanning_alert_list",
    "secret_scanning_alert_get",
    "secret_scanning_alert_locations",
    "workflow_dispatch",
    "workflow_run_rerun",
    "workflow_run_cancel",
];

pub const PRIMARY_TOOL_NAMES: &[&str] = &[
    "terminal_exec",
    "directory_list",
    "file_search",
    "text_search",
    "file_read",
    "file_read_multiple",
    "file_edit",
    "file_write",
    "apply_patch",
    "workspace_bootstrap",
    "workspace_add",
    "workspace_list",
    "workspace_get",
    "workspace_remove",
];
