use super::*;

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            port: DEFAULT_PORT,
            mode: SecurityMode::Local,
            dir: None,
            origin: None,
            allowed_hosts: Vec::new(),
            oauth_secret: None,
            oauth_issuer: None,
            oauth_audience: None,
            oauth_owner_subject: None,
            execution_root: None,
            bind_host: "127.0.0.1".into(),
            trusted_proxy: false,
            trusted_proxy_cidr: None,
            default_terminal_timeout_ms: 30_000,
            max_terminal_timeout_ms: 60_000,
            completed_job_ttl_ms: 3_600_000,
            max_retained_output_bytes: 1_048_576,
            max_running_jobs: 16,
            allow_terminal_network: false,
            allow_ssh: false,
            ssh_root: None,
            ssh_config: None,
            ssh_readonly_db_user: None,
            ssh_readonly_redis_user: None,
            ssh_readonly_redis_password_file: None,
            allow_docker: false,
            docker_socket: "/var/run/docker.sock".into(),
            allow_tailscale: false,
            tailscale_socket: "/var/run/tailscale/tailscaled.sock".into(),
            toolchain_paths: Vec::new(),
            lsp_servers: Vec::new(),
            enable_creative: false,
            blender_executable: None,
            blender_bridge_port: blender::DEFAULT_BLENDER_BRIDGE_PORT,
            blender_bridge_timeout_ms: 30_000,
            creative_binding_descriptors: Vec::new(),
            creative_binding_backends: Vec::new(),
            creative_approval_compute_units: 5_000,
            creative_job_hard_compute_units: 50_000,
            creative_project_hard_compute_units: 500_000,
            creative_max_job_output_bytes: 64 * 1024 * 1024,
            creative_max_concurrent_jobs: 4,
            creative_max_retries: 2,
            enable_agent_hooks: false,
            agent_hooks_config: None,
            tool_profile: ToolProfile::Full,
            activity: ActivityConfig::default(),
            telegram_enabled: false,
            workspaces: default_workspaces(),
        }
    }
}
