use super::*;

pub(super) fn workflows() -> Vec<WorkflowDescriptor> {
    vec![
        workflow(
            "sequence_assemble",
            "Assemble ordered accepted shot/video Assets and optional audio through a caller-selected compatible video binding.",
            &["video.sequence_assemble"],
            json!({
                "type":"object",
                "properties":{
                    "video_asset_ids":id_array(1,128),
                    "audio_asset_ids":id_array(0,64),
                    "fps":{"type":"number","minimum":1,"maximum":240},
                    "width":{"type":"integer","minimum":16,"maximum":16384},
                    "height":{"type":"integer","minimum":16,"maximum":16384},
                    "transitions":{"type":"array","maxItems":127,"items":short_string(64)}
                },
                "required":["video_asset_ids","fps","width","height"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "export_profile",
            "Create a contained export receipt for selected accepted Assets; export never deploys or publishes.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "asset_ids":id_array(1,128),
                    "profile":{"type":"string","enum":["video","still","project","character","world"]},
                    "file_name":short_string(128)
                },
                "required":["asset_ids","profile","file_name"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "project_handoff",
            "Create a contained human-readable production handoff manifest from durable project state, selected revisions, assets, and QA.",
            &[],
            json!({
                "type":"object",
                "properties":{"label":short_string(128)},
                "required":["label"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "scene_continuity_review",
            "Generate deterministic cross-shot continuity evidence and bounded QA findings without fabricating subjective review.",
            &[],
            json!({
                "type":"object",
                "properties":{"scene_id":id_schema()},
                "required":["scene_id"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "visual_qa_evidence",
            "Package bounded visual references/previews and deterministic evidence; semantic judgment remains not_inspected unless an evaluator binding is explicitly requested.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "subject_id":id_schema(),
                    "source_revision_id":id_schema(),
                    "asset_id":id_schema(),
                    "reference_asset_ids":id_array(0,32),
                    "preview_asset_ids":id_array(0,32),
                    "evaluator_binding_id":id_schema()
                },
                "required":["subject_id"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "temporal_qa_evidence",
            "Package bounded timing/frame evidence for temporal review; semantic identity/motion judgment remains not_inspected without an explicit evaluator binding.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "subject_id":id_schema(),
                    "source_revision_id":id_schema(),
                    "asset_id":id_schema(),
                    "duration_ms":{"type":"integer","minimum":1,"maximum":86400000},
                    "sample_frames":{"type":"array","maxItems":128,"items":{"type":"integer","minimum":0,"maximum":10000000}},
                    "evaluator_binding_id":id_schema()
                },
                "required":["subject_id"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "scoped_revision",
            "Create a lineaged child revision receipt for one caller-declared change scope while preserving unrelated locked state.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "parent_asset_id":id_schema(),
                    "changed_scope":{"type":"string","enum":["expression","pose","background_lighting","camera_framing","palette_accent","hair_clothing_clipping","shot_timing","material_shader"]},
                    "locked_fields":{"type":"array","maxItems":64,"uniqueItems":true,"items":short_string(128)},
                    "requested_change":{}
                },
                "required":["parent_asset_id","changed_scope"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "promo_pack",
            "Package accepted anime/game promotional assets through the shared delivery kernel; no deploy or publish occurs.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "asset_ids":id_array(1,64),
                    "element_ids":id_array(0,64),
                    "output_profile":short_string(64)
                },
                "required":["asset_ids"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "key_visual_bundle",
            "Package accepted key visual, cover, and thumbnail assets while preserving Element/Asset lineage and separate publish authority.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "asset_ids":id_array(1,64),
                    "element_ids":id_array(0,64),
                    "output_profile":short_string(64)
                },
                "required":["asset_ids"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "portfolio_delivery",
            "Package accepted creative assets for a source-preserving portfolio/app workflow; build/test/deploy remain existing generic capabilities and publish remains separate.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "asset_ids":id_array(1,64),
                    "element_ids":id_array(0,64),
                    "output_profile":short_string(64)
                },
                "required":["asset_ids"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "voice_clone",
            "Create an authorized reusable voice artifact from bounded voice references.",
            &["audio.voice_clone"],
            json!({
                "type":"object",
                "properties":{
                    "reference_asset_ids":id_array(1,16),
                    "consent_asserted":{"const":true},
                    "language":short_string(32)
                },
                "required":["reference_asset_ids","consent_asserted"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "voice_change",
            "Create a lineaged voice-changed audio child asset.",
            &["audio.voice_change"],
            json!({
                "type":"object",
                "properties":{"asset_id":id_schema(),"voice_element_id":id_schema()},
                "required":["asset_id","voice_element_id"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "video_dub",
            "Create synchronized dubbed media from a contained source video and voice plan.",
            &["audio.video_dub"],
            json!({
                "type":"object",
                "properties":{
                    "video_asset_id":id_schema(),
                    "voice_element_id":id_schema(),
                    "language":short_string(32)
                },
                "required":["video_asset_id","voice_element_id","language"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "shot_render_preview",
            "Execute one caller-authored shot through a selected backend.",
            &["video.reference_generate"],
            json!({
                "type":"object",
                "properties":{"scene_id":id_schema(),"shot_id":id_schema()},
                "required":["scene_id","shot_id"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "game_asset_batch",
            "Run caller-declared independent game asset jobs.",
            &["image.generate", "audio.sfx"],
            json!({
                "type":"object",
                "properties":{
                    "game_id":id_schema(),
                    "roles":{"type":"array","minItems":1,"maxItems":128,"uniqueItems":true,"items":short_string(128)}
                },
                "required":["game_id","roles"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "game_source_scaffold",
            "Create a normal human-editable reviewed browser-game source scaffold from the stored Game Manifest without choosing creative design for the caller.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "game_id":id_schema(),
                    "template_family":{"type":"string","enum":["2d_canvas","3d_webgl"]}
                },
                "required":["game_id","template_family"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "game_build_playtest",
            "Materialize stable manifest assets, build the reviewed browser-game scaffold, and emit deterministic local playtest evidence.",
            &[],
            json!({
                "type":"object",
                "properties":{"game_id":id_schema(),"source_revision":id_schema()},
                "required":["game_id"],
                "additionalProperties":false
            }),
            json!({
                "type":"object",
                "properties":{
                    "build_id":id_schema(),
                    "playtest_evidence_id":id_schema()
                },
                "required":["build_id","playtest_evidence_id"],
                "additionalProperties":false
            }),
        ),
        workflow(
            "game_deploy",
            "Deploy one QA-accepted game build through an explicitly selected deployment binding without public publication.",
            &["game.deploy"],
            json!({
                "type":"object",
                "properties":{"game_id":id_schema(),"build_revision":id_schema()},
                "required":["game_id","build_revision"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
        workflow(
            "game_iteration",
            "Record a source-preserving game iteration and invalidate only build/playtest state affected by caller-declared changed fields.",
            &[],
            json!({
                "type":"object",
                "properties":{
                    "game_id":id_schema(),
                    "changed_fields":{"type":"array","minItems":1,"maxItems":128,"uniqueItems":true,"items":short_string(128)},
                    "gameplay_impacting":{"type":"boolean"}
                },
                "required":["game_id","changed_fields","gameplay_impacting"],
                "additionalProperties":false
            }),
            asset_output(),
        ),
    ]
}
