use super::*;

pub fn capabilities() -> Vec<CapabilityDescriptor> {
    vec![
        capability_descriptor(
            "image.generate",
            "image",
            true,
            &[],
            &["image"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "image.reference_generate",
            "image",
            true,
            &["reference_image"],
            &["image"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "image.edit",
            "image",
            true,
            &["image"],
            &["image"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "image.inpaint",
            "image",
            true,
            &["image", "mask"],
            &["image"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "image.upscale",
            "image",
            true,
            &["image"],
            &["image"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "image.remove_background",
            "image",
            true,
            &["image"],
            &["image_alpha"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "image.outpaint",
            "image",
            true,
            &["image"],
            &["image"],
            &["network_or_compute", "workspace_write"],
        ),
        identity_prepare_descriptor(),
        capability_descriptor(
            "video.generate",
            "video",
            true,
            &[],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.image_to_video",
            "video",
            true,
            &["reference_image"],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.reference_generate",
            "video",
            true,
            &["reference_image"],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.extend",
            "video",
            true,
            &["video"],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.reframe",
            "video",
            true,
            &["video"],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.upscale",
            "video",
            true,
            &["video"],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.remove_background",
            "video",
            true,
            &["video"],
            &["video_alpha"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.motion_control",
            "video",
            true,
            &["reference_image", "motion_reference"],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.clip_extract",
            "video",
            true,
            &["video"],
            &["video_clip"],
            &["compute", "workspace_write"],
        ),
        capability_descriptor(
            "video.sequence_assemble",
            "video",
            true,
            &["video_clip", "audio"],
            &["video"],
            &["compute", "workspace_write"],
        ),
        capability_descriptor(
            "audio.speech",
            "audio",
            true,
            &[],
            &["audio"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "audio.voice",
            "audio",
            true,
            &[],
            &["audio"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "audio.music",
            "audio",
            true,
            &[],
            &["audio"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "audio.sfx",
            "audio",
            true,
            &[],
            &["audio"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "audio.voice_clone",
            "audio",
            true,
            &["voice_reference"],
            &["voice_artifact"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "audio.voice_change",
            "audio",
            true,
            &["audio"],
            &["audio"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "audio.video_dub",
            "audio",
            true,
            &["video", "voice_reference"],
            &["video"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "3d.image_to_mesh",
            "3d",
            true,
            &["reference_image"],
            &["mesh"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "3d.text_to_mesh",
            "3d",
            true,
            &[],
            &["mesh"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "3d.texture",
            "3d",
            true,
            &["mesh", "reference_image"],
            &["mesh"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "3d.rig_bootstrap",
            "3d",
            true,
            &["mesh"],
            &["rigged_mesh"],
            &["network_or_compute", "workspace_write"],
        ),
        capability_descriptor(
            "storyboard.store",
            "scene",
            false,
            &["element_reference"],
            &["storyboard"],
            &["workspace_write"],
        ),
        capability_descriptor(
            "scene.manifest_validate",
            "scene",
            false,
            &["element_reference"],
            &["scene_manifest"],
            &["workspace_read"],
        ),
        capability_descriptor(
            "graph.validate",
            "graph",
            false,
            &[],
            &["graph_validation"],
            &["workspace_read"],
        ),
        capability_descriptor(
            "graph.execute",
            "graph",
            false,
            &[],
            &["graph_run"],
            &["workspace_write"],
        ),
        capability_descriptor(
            "dcc.execute",
            "dcc",
            false,
            &["asset"],
            &["asset"],
            &["privileged_bridge", "workspace_write"],
        ),
        capability_descriptor(
            "dcc.render",
            "dcc",
            false,
            &["scene"],
            &["image", "video"],
            &["privileged_bridge", "compute", "workspace_write"],
        ),
        capability_descriptor(
            "game.build",
            "game",
            false,
            &["game_source", "asset"],
            &["game_build"],
            &["process_exec", "workspace_write"],
        ),
        capability_descriptor(
            "game.playtest",
            "game",
            false,
            &["game_build"],
            &["playtest_evidence"],
            &["process_exec", "workspace_read"],
        ),
        capability_descriptor(
            "game.deploy",
            "game",
            true,
            &["game_build"],
            &["deployment"],
            &["network_write", "external_mutation"],
        ),
    ]
}
