use axum::extract::Request;
use axum::http::{HeaderMap, HeaderName, StatusCode};
use serde_json::json;
use std::time::Instant;

const MAX_LOG_FIELD: usize = 128;
const HDR_CORRELATION_ID: &str = "x-correlation-id";
const HDR_REQUEST_ID: &str = "x-request-id";

pub fn safe_log_field(value: &str) -> String {
    value
        .chars()
        .filter(|c| !c.is_control())
        .take(MAX_LOG_FIELD)
        .collect()
}

pub fn privacy_id(value: Option<&str>) -> &'static str {
    if value.is_some() {
        "present"
    } else {
        "absent"
    }
}

/// A client-supplied `x-correlation-id` header value, retained ONLY as
/// untrusted optional metadata (Plan 035 Phase 9). It is bounded/sanitized on
/// extraction, may be attached to private telemetry for support correlation,
/// and is NEVER treated as the authoritative request identity and NEVER set
/// on the response — see [`RequestId`] for the server-generated authoritative
/// identity.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CorrelationId(Option<String>);

impl CorrelationId {
    pub fn from_request(req: &Request) -> Self {
        Self::from_headers(req.headers())
    }
    fn from_headers(headers: &HeaderMap) -> Self {
        let id = headers
            .get(HDR_CORRELATION_ID)
            .and_then(|value| value.to_str().ok())
            .filter(|value| {
                value.len() <= MAX_LOG_FIELD
                    && value.chars().all(|c| c.is_ascii_graphic() && c != '"')
            })
            .map(str::to_owned);
        Self(id)
    }
    /// The sanitized client hint, if the caller supplied a well-formed one.
    /// Untrusted metadata only — never use as an authoritative identity.
    pub fn as_str(&self) -> Option<&str> {
        self.0.as_deref()
    }
}

/// Server-generated request identity (Plan 035 Phase 9). This is the
/// authoritative correlation value for one inbound request: it is always
/// generated by this process (never taken from client input), returned to
/// the client on every response via the `x-request-id` header, and safe to
/// echo back in a generic 5xx body so a client can hand it to support.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RequestId(String);

impl RequestId {
    pub fn generate() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }
    pub fn as_str(&self) -> &str {
        &self.0
    }
    pub fn insert_response_header(&self, response: &mut axum::response::Response) {
        if let Ok(value) = self.as_str().parse() {
            response
                .headers_mut()
                .insert(HeaderName::from_static(HDR_REQUEST_ID), value);
        }
    }
}

/// Emits the `relay.request` audit event to stderr (and, when the OTel
/// bridge from `telemetry.rs` is active, into the current tracing span as a
/// structured event). `request_id` is the server-generated authoritative
/// identity; `client_hint` is the untrusted, optional client-supplied
/// correlation metadata (never authoritative, never returned to the client).
#[allow(clippy::too_many_arguments)]
pub fn audit(
    request_id: &str,
    client_hint: Option<&str>,
    method: &str,
    tool: Option<&str>,
    outcome: &str,
    status: StatusCode,
    started: Instant,
    subject: Option<&str>,
) {
    let latency_ms = started.elapsed().as_millis();
    tracing::info!(
        event = "relay.request",
        request_id = safe_log_field(request_id),
        method = safe_log_field(method),
        tool = privacy_id(tool),
        outcome = safe_log_field(outcome),
        status = status.as_u16(),
        latency_ms = latency_ms as u64,
        subject = privacy_id(subject),
    );
    eprintln!(
        "{}",
        json!({"event":"relay.request","request_id":safe_log_field(request_id),
        "client_hint":client_hint.map(safe_log_field),
        "method":safe_log_field(method),"tool":privacy_id(tool),"outcome":safe_log_field(outcome),
        "status":status.as_u16(),"latency_ms":latency_ms,"subject":privacy_id(subject)})
    );
}
