import { readFileSync } from 'node:fs'

function read(path: string) {
  return readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8')
}

function requireText(source: string, needle: string, message: string) {
  if (!source.includes(needle)) throw new Error(message)
}

const schema = read('server/database/schema.ts')
const migration = read('server/database/migrations/0018_mean_lethal_legion.sql')
const session = read('server/application/auth-session.ts')
const middleware = read('server/middleware/api-auth.ts')
const authDb = read('server/infrastructure/database/auth.ts')
const mfaDb = read('server/infrastructure/database/mfa.ts')
const totp = read('server/infrastructure/security/totp.ts')
const recovery = read('server/application/mfa.ts')
const csrf = read('server/middleware/csrf.ts')
const headers = read('server/middleware/security-headers.ts')
const contentType = read('server/middleware/content-type.ts')
const settings = read('server/api/settings.put.ts')
const emailChange = read('server/api/auth/email-change.post.ts')
const passwordScreening = read('server/infrastructure/security/password-screening.ts')
const landing = read('app/pages/index.vue')

requireText(schema, 'export const authSessions', 'browser sessions must have a durable table')
requireText(schema, 'secretHash: text(\'secret_hash\').notNull().unique()', 'browser bearer secrets must only be persisted as unique hashes')
requireText(schema, 'export const mfaFactors', 'MFA factors must have a durable table')
requireText(schema, 'secretEncrypted: text(\'secret_encrypted\').notNull()', 'TOTP seeds must be encrypted at rest')
requireText(schema, 'export const mfaRecoveryCodes', 'recovery codes must have a durable table')
requireText(schema, 'codeHash: text(\'code_hash\').notNull().unique()', 'recovery codes must be hashed and unique')
requireText(schema, 'export const securityEvents', 'security events must be durably stored')
requireText(migration, 'CREATE TABLE "ai_code"."auth_sessions"', 'session migration must exist')
requireText(migration, 'CREATE TABLE "ai_code"."mfa_factors"', 'MFA migration must exist')
requireText(migration, 'CREATE TABLE "ai_code"."security_events"', 'security-event migration must exist')
requireText(session, 'randomBytes(32)', 'browser sessions need high-entropy opaque secrets')
requireText(session, 'createHash(\'sha256\')', 'browser session validation must hash the presented secret')
requireText(middleware, 'validateAuthSession', 'middleware must owner-scope browser-session validation')
requireText(middleware, 'apiKeyAuthenticated', 'API-key seeded sessions must not bypass browser-session validation')
requireText(middleware, 'sessionUser.role !== current.role', 'role changes must invalidate stale claims')
requireText(authDb, 'authSessions).set({ revokedAt: now })', 'credential resets must revoke active browser sessions')
requireText(authDb, 'isNull(verificationTokens.consumedAt)', 'verification tokens must reject replay')
requireText(authDb, 'gt(verificationTokens.expiresAt, now)', 'verification tokens must reject expiry')
requireText(mfaDb, 'isNull(mfaRecoveryCodes.usedAt)', 'recovery codes must be atomically single-use')
requireText(totp, 'timingSafeEqual', 'TOTP comparison must be timing-safe')
requireText(recovery, 'randomBytes(8)', 'recovery codes must be generated from cryptographic randomness')
requireText(csrf, 'Invalid request origin', 'state-changing API requests must enforce same-origin when Origin is present')
requireText(headers, 'Cache-Control', 'API responses must be non-cacheable')
requireText(headers, 'X-Content-Type-Options', 'security response headers must be installed centrally')
requireText(contentType, 'application/json', 'mutation APIs must reject unsupported content types')
if (settings.includes('email: v.optional')) throw new Error('settings must not accept mutable primary-email updates')
requireText(emailChange, 'verifyPassword', 'email changes must require current-password proof')
requireText(emailChange, 'requestEmailChange', 'email changes must remain pending until confirmation')
requireText(passwordScreening, 'api.pwnedpasswords.com/range/', 'password screening must use a privacy-preserving range lookup')
requireText(passwordScreening, 'SCREENING_TIMEOUT_MS', 'password screening must have a bounded timeout')
if (passwordScreening.includes('password}&') || passwordScreening.includes('password}`')) throw new Error('plaintext passwords must not enter screening request URLs')
if (mfaDb.includes('select().from(mfaRecoveryCodes)')) throw new Error('recovery-code reads must not expose stored hashes')
if (landing.includes('style=') || landing.includes('v-html') || landing.includes('innerHTML')) throw new Error('landing page must not add inline-style or raw-HTML sinks')

console.log('account-security: OK')
